version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    image: fullee/mysql:4.0.27
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
    #  - ./volume/conf/my.cnf:/etc/my.cnf
      - ./volume/data:/data
    ports:
      - "3316:3306"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
